Adjlist
pysal/libpysal pull request #321
Opened 2020-07-14 17:47 UTC by ljwolf

Hello! Please make sure to check all these boxes before submitting a Pull Request
(PR). Once you have checked the boxes, feel free to remove all text except the
justification in point 5. 

1. [x] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on your changes?
2. [x] This pull request is directed to the `pysal/master` branch.
3. [x] This pull introduces new functionality covered by
   [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and
   [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [x] You have [assigned a
   reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/)
5. [x] The justification for this PR is: 
Adjacency lists are one of the three major representations of graphs. We need to figure out how to accurately represent islands in their structure, rather than simply warning that islands will be dropped. I propose using a simple syntax, where the `neighbor_id` of an island is set to `None` and the weight to `numpy.nan`. This PR provides this in the `to_adjlist()` method, and will examine (and fix) the `from_adjlist()` method if necessary.

2020-07-14 18:07 UTC, ljwolf commented
Actually, there's a type consistency issue with using the neighbor_id` as `None`, since that changes the `dtype` of `adjlist.neighbor`. 

So, @sjsrey's initial proposal is probably the right way to deal with this:
> what about adding a self-loop with zero weight?

2020-07-15 09:36 UTC, ljwolf commented
seems to be an issue with round-tripping the weights when IDs are used. I am not sure, but I have seen this keyerror before when building weights from a dictionary with non-integer ids.

2020-07-15 14:51 UTC, ljwolf commented
The issue ended up being #322 
I have put a workaround in the tests to avoid this issue. 

I can include the suggested fix to #322 if approved?

2020-07-15 16:51 UTC, ljwolf commented
The test failures appear to be on code that I've changed. But, in the traceback, the code is *not* changed. This is odd! Any advice?

2020-07-15 17:03 UTC, jGaboardi commented
> The test failures appear to be on code that I've changed. But, in the traceback, the code is _not_ changed. This is odd! Any advice?

Is odd... GitHub seems to be a bit funky today. Maybe try another empty commit to the PR to see if that triggers the correct code for the GHA? Also, looks like I was added and removed as a reviewer here, but still listed as a reviewer along with Wei. Review desired or not?

2020-07-16 09:35 UTC, ljwolf commented
Not sure why folks were removed from the request? I had intended to get @weikang9009 @jGaboardi and @sjsrey

2020-07-16 14:59 UTC, jGaboardi commented
> The test failures appear to be on code that I've changed. But, in the traceback, the code is _not_ changed. This is odd! Any advice?

Can confirm that your changes pass locally.

2020-07-16 16:33 UTC, jGaboardi commented
> The issue ended up being #322
> I have put a workaround in the tests to avoid this issue.
> 
> I can include the suggested fix to #322 if approved?

I think the inclusion of #322 is a good idea, pending an explanation of the set name (`out_islands`).

2020-07-19 05:35 UTC, weikang9009 commented on libpysal/weights/weights.py
> +        n_islands = len(self.islands)
`n_islands` is not further used and could be dropped.

2020-08-07 15:35 UTC, ljwolf commented
Fixing #322 is not as simple, since this affects most of the rest of the weights id machinery. 

I'd suggest we merge this for now, and address #322 in the project about refactoring the weights.

2020-10-05 16:25 UTC, martinfleis requested changes
I have a few points here.

1) This is a breaking change. If you do not care about weights but want to know neighbours to do other things, this adds a new row which may affect the result. For example, if I want to know all pairs and measure mean distance between them, this adds 0 and affects the value (this would in fact break one function in momepy).

2) Can we add a keyword like `include_islands` to control this behaviour? In the example above, I just do not want them at all since they do not have neighbours. This could start with `False` as a default with a warning that in the future it will be `True` to avoid a hard breaking change here.

2020-12-10 03:30 UTC, sjsrey approved these changes

2021-09-03 10:55 UTC, ljwolf commented
I've addedthe option outlined by @martinfleis, and I've set it so that, by default, islands are dropped. I would like to transition to *not* dropping islands quite quickly, as formats should not be lossy.... to_adjlist()/from_adjlist() should be inverses, and they're not at the moment. 

This is now needed for bugfixes over in [pysal/esda#190](https://github.com/pysal/esda/pull/190), so I hope to merge & cut a point release shortly.

2021-09-03 12:39 UTC, martinfleis commented
We can do what we often do in geopandas. Set `drop_islands=None` and warn that this now defaults to True but it will default to False in the future. If you set it manually to True/False, no warning. Then, in the next release, we can change the default to False and remove the warning.

2021-09-08 20:25 UTC, ljwolf commented
Great, have done this!

2021-09-08 20:47 UTC, martinfleis commented
The default value on line 278 should be `None`, not `True`.

2021-09-08 21:26 UTC, ljwolf commented
Yep, sorry again; I had a local issue with ce1b1eb, so I rolled back & redid the changes manually. Missed that. Thanks!

2021-09-08 22:45 UTC, martinfleis approved these changes
Thanks!

2021-09-09 08:39 UTC, merged