Rastint opti
pysal/libpysal pull request #343
Opened 2020-08-28 19:20 UTC by MgeeeeK

This pull request adds a new optimized weight builder for the raster interface.

Main takeaway:
- Sparse matrix is build using rows and cols values which are generated iteratively. 
- The parallel implementation is based on the crand engine from [esda/#116](https://github.com/pysal/esda/pull/116), though this work uses `threading` backend.
- This pr also adds functionality to add `higher_order` neighbors, this is done using 2 ways:
  - Firstly, 2 arguments are added to the builder method (`k=int` and `include_nas=boolean`). `k` is used for specifying the kth order and `include_nas=True` is used for including higher-order neighbors even if lower-order neighbors are missing.
  - `higher_order` functionality is based on the suggestion provided by Martin in this issue [libpysal/#issue313](https://github.com/pysal/libpysal/issues/313). This also adds diagonal elements that are first converted to zero and then these zero elements are removed in the last step. But this changes the sparsity of the matrix!.
  - If `include_nas` is `True` then the method simply uses modular arithmetic to add higher-order neighbors. (with one caveat explained earlier and in this thread [libpysal/#328](https://github.com/pysal/libpysal/issues/328#issuecomment-664948667))
  
You can check this [notebook](https://github.com/MgeeeeK/libpysal/blob/rastint_opti/notebooks/Raster_awareness_API.ipynb) ( cell _20-22_ ) to get an idea of the API and different `higher_order` approach.

2020-09-26 20:07 UTC, sjsrey commented
I can see the logic of offering the option for `include_nas`. So I'm +1 on that. I'm wondering if there is a more informative name for the argument, possibly? I'm not clear on what `nas` stands for?

2020-09-28 12:47 UTC, MgeeeeK commented
Sure! we can rename that argument. What do you guys suggest @darribas @slumnitz?
I think we assigned that as the temporary name because the functionality was not fully finalized.

2020-12-23 17:47 UTC, darribas requested changes
Almost there!!! Mostly issues of documentation and style, the only more substantive bit is to ensure the `id_order` of the weights we build is relatable to the `DataArray`

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/tests/test_raster.py
>          w1 = raster.da2WSP(self.da1, "queen")
I _think_ this file misses testing building a rook matrix on multi-core? Check, it might be an easy one to add to increase coverage.

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/contiguity.py
> +        include_nas : boolean
Same as above, make sure it's replaced throughout

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
> +    n_jobs : int
Add what's the default

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
>         instance of spatial weights class WSP
Here it might be good also to add more information about the index built

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
> +        id_map = ids.copy()
Make sure this is tested

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
> +            "falling back to inefficient method"
Maybe replace "inefficient method" by "slower version"

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
> +            "Cannot convert deprecated W with no index attribute")
I'd replace the message by on that is more informative about what is required. Maybe something like:

```
`w` requires to include a `index` attribute that is built as a `pandas.MultiIndex` object. This will be used to build the coords in the resulting `da`
```

Something like that, you might have to tweak the message a bit with some of the information you include in the description of the index built by `da2WSP`

The future structure of weights object is still a bit in flux, so I'd not give the impression that is clear and the current one will be phased out.

Replace in all instance (it's on a couple other places)

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
> +        raise ValueError("da must be an array of integers or float")
This should be another easy one to test to increase coverage

2020-12-23 17:47 UTC, darribas commented on libpysal/weights/raster.py
> +    wsp = WSP(sw, index=ser.index, id_order=ids.tolist())
I'd vote here to use `sw.index.tolist()` as the values for `id_order`. It's repetition but it's better for consistency and allows us to be more backwards compatible with the traditional model, but also to support the idea of an `index` approach to weights

2021-01-04 09:39 UTC, darribas requested changes
Just a couple minor bits to add, only docs and tests and I think this is good to ship!

2021-01-04 09:39 UTC, darribas commented on libpysal/weights/raster.py
>         instance of spatial weights class WSP
Please add a short description about the `index` attribute that `wsp` is returned with, since this will not be the same across the library. Something like: "instance of spatial weights class WSP with an `index` attribute that includes a MultiIndex object from the DataArray"

2021-01-04 09:39 UTC, darribas commented on libpysal/weights/tests/test_raster.py
>          w1 = raster.da2WSP(self.da1, "queen")
Has this been added?

2021-01-08 19:42 UTC, slumnitz commented on libpysal/weights/raster.py
> +        id_map = ids.copy()
This is one of the last follow ups, I still detect.

2021-01-08 19:50 UTC, slumnitz commented on libpysal/weights/tests/test_raster.py
>          w1 = raster.da2WSP(self.da1, "queen")
This still seems outstanding @MgeeeeK

2021-01-08 19:53 UTC, slumnitz commented on libpysal/weights/raster.py
> +        raise ValueError("da must be an array of integers or float")
@MgeeeeK you can test if a ValueError is raised here, this is the only line not covered, the rest seems good to go now.

2021-01-08 19:53 UTC, slumnitz commented on libpysal/weights/raster.py
> +        id_map = ids.copy()
Codecov indicates that it is currently not tested.

2021-01-08 19:55 UTC, slumnitz commented on libpysal/weights/raster.py
> +            "Cannot convert deprecated W with no index attribute")
Looks good to me, what do you think @darribas?

2021-01-08 19:58 UTC, slumnitz commented on libpysal/weights/contiguity.py
Documentation looks great! This is resolved? What do you think @darribas?

2021-01-08 20:04 UTC, slumnitz requested changes
@MgeeeeK this looks great and I think we are super close to merging. The only thing remaining is to test a couple more lines. I resolved all of @darribas comments that where addressed and looked great. There are a couple minor comments still standing that slipped through the radar and are still open (even if marked outdated). Once these are added I am happy to get this merged. Thank you so much for your hard work this and last year!

2021-01-10 06:59 UTC, MgeeeeK commented on libpysal/weights/tests/test_raster.py
>          w1 = raster.da2WSP(self.da1, "queen")
oops my bad...

2021-01-10 13:30 UTC, darribas reviewed
I've resolved a couple of the standing threads, they look good. I'm not sure `test_da2WSP` is being fully tested. I can see `rook` and `queen` are now both tested, but it's always in the multi-core context. Is it a different bit of code that runs it on single core? If not, it's fine, but if it is, we should test that too.

2021-01-10 13:30 UTC, darribas commented on libpysal/weights/contiguity.py
This looks good to go, resolved

2021-01-10 14:20 UTC, MgeeeeK commented
> Is it a different bit of code that runs it on single core?
No, multi-thread is extension of the base constructor but still I'll add another test comparing results of multi-threaded and single-threaded builder.

2021-01-10 14:30 UTC, MgeeeeK commented on libpysal/weights/tests/test_raster.py
> +        w2 = raster.da2WSP(self.da2, "queen", k=2, include_nodata=True)
Test for single and multi-threaded results, this also compares `include_nodata = True` and `include_nodata = False` for `k=2` (Since there is no missing value, output in both the case will be same)

2021-01-22 17:12 UTC, darribas commented
I think this is good to go as far as I'm concerned. @slumnitz ? If both give it green light, I think @sjsrey or us can merge?

2021-01-22 17:12 UTC, darribas approved these changes

2021-01-22 20:25 UTC, slumnitz approved these changes
Let's get this merged then! :)

2021-01-25 09:12 UTC, merged