Test graph class
pysal/libpysal pull request #536
Opened 2023-07-28 16:59 UTC by martinfleis

This is just a start, no need to merge yet. I'll continue later today a bit and then after the weekend.

2023-07-29 14:52 UTC, martinfleis commented
I have included `to_W` and `from_W` in this PR to allow easy roundtripping. We can use `to_W` in downstream for an easy compatibility layer.

2023-07-30 22:17 UTC, martinfleis commented
This is now ready for a review and merge. It contains test suite for most of the contents of `base.py`. It does not include tests of any of the `build_*` constructors.

It also contains a number of fixes I've found through tests and a few new methods I needed (W I/O. copy).

2023-07-30 22:56 UTC, jGaboardi requested changes
Mostly minor stuff. Very good work. I am guessing yall decided to swap `islands` terminology to `isolates` in one of the recent sprints?

2023-07-30 22:56 UTC, jGaboardi commented on libpysal/graph/_utils.py
> +        data_array = pd.Series(weights).explode().fillna(0).values
I am guessing since this is a very internal function that hard coding a `0` here is the only acceptable value for filling `NA`?

2023-07-30 22:56 UTC, jGaboardi commented on libpysal/graph/base.py
> +            list-like of ids for focal geometries that is mappable to
Should this one read `focal geometries` or `neighbor geometries`?

2023-07-30 22:56 UTC, jGaboardi commented on libpysal/graph/base.py
> +            standardized = (s * nQ).fillna(0).values  # isolate comes as NaN -> 0
Same here for hard coding a `0` for filling `NA`. Would there never be any chance a user would want/need to use another value for filling `NA`?

2023-07-30 22:56 UTC, jGaboardi commented on libpysal/graph/base.py
> +            I.e. ``True`` requires equality of the weight to consider
Very small nitpick, but I think this should be "e.g." (could be wrong though).

2023-07-30 22:56 UTC, jGaboardi commented on libpysal/graph/tests/test_base.py
> +    def test_from_dicts_via_W(self, y, id_type, rook):
Very minor nit: Perhaps we should swap the `"rook"` and `"id_type"` markers to match the order of the positional arguments in `test_from_dicts_via_W`?

2023-07-30 22:57 UTC, jGaboardi commented
Curious about the Ubuntu 3.8 and Windows 3.11 failures.

2023-07-31 07:16 UTC, martinfleis commented on libpysal/graph/_utils.py
> +        data_array = pd.Series(weights).explode().fillna(0).values
Always 0. Weights of an isolate (island) are `[]` which gets converted to missing by `explode`. We always need to encode that with 0.

2023-07-31 07:18 UTC, martinfleis commented on libpysal/graph/base.py
> +            standardized = (s * nQ).fillna(0).values  # isolate comes as NaN -> 0
Nope, always 0. When a weight is 0, these ops result in it being np.nan at one point but all we want is to keep a 0. For both isolates and zero-weight neighbours.

2023-07-31 07:20 UTC, martinfleis commented
>  I am guessing yall decided to swap islands terminology to isolates in one of the recent sprints?

As per @ljwolf's suggestion to match the [ecosystem](https://networkx.org/documentation/stable/reference/algorithms/isolates.html#module-networkx.algorithms.isolate).


> Curious about the Ubuntu 3.8 and Windows 3.11 failures.

They're not related to these changes (apart from that one in 3.8 I'll look into) so I ignored them for now.

2023-07-31 07:34 UTC, martinfleis commented
There's also some flaky-ness with pytest-xdist but none of that related to this PR, so I suppose nothing stops from merging this.

2023-08-03 20:35 UTC, martinfleis commented
Merging in the spirit of fact-paced development :)

2023-08-03 20:36 UTC, merged