[WIP] Matching
pysal/libpysal pull request #666
Opened 2023-12-08 18:22 UTC by ljwolf

Hello! Please make sure to check all these boxes before submitting a Pull Request
(PR). Once you have checked the boxes, feel free to remove all text except the
justification in point 5. 

1. [ ] You have run tests on this submission locally using `pytest` on your changes. Continuous integration will be run on all PRs with [GitHub Actions](https://github.com/pysal/libpysal/blob/master/.github/workflows/unittests.yml), but it is good practice to test changes locally prior to a making a PR.
2. [ ] This pull request is directed to the `pysal/master` branch.
3. [x] This pull introduces new functionality covered by
   [docstrings](https://en.wikipedia.org/wiki/Docstring#Python) and
   [unittests](https://docs.python.org/2/library/unittest.html)? 
4. [ ] You have [assigned a
   reviewer](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) and added relevant [labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/)
5. [x] The justification for this PR is contained in #665

2023-12-08 18:25 UTC, ljwolf commented on libpysal/graph/_matching.py
> +    p : int (default: 2)
This isn't being sent to metric at the moment.

2023-12-08 18:28 UTC, ljwolf commented on libpysal/graph/_matching.py
> +                    match_vars.get((i, j), match_vars.get((j, i)))
The problem is much more efficient when `x=y`, and we can implement this trick to halve the number of decision variables. If we recursively solved `_spatial_matching(x=x, y=x)`, we'd lose this optimisation. I *think* this optimisation also would work if `x.shape==y.shape`.

2023-12-08 23:20 UTC, ljwolf commented on libpysal/graph/_matching.py
> +                    match_vars.get((i, j), match_vars.get((j, i)))
No, the only reason why the upper triangle works is because the rows are exchangeable with the columns. If you had a 3 x 5 matching matrix, neither triangle can express the full set of possible matches.

All cases where x != y need the full assignment matrix, and we can only use the upper/lower triangle if y=x.

2023-12-10 16:43 UTC, ljwolf commented
Tests are now added, but pulp installation fails on windows through `conda-forge`. Is there a better way to do this?

2023-12-10 16:46 UTC, jGaboardi commented
> Tests are now added, but pulp installation fails on windows through `conda-forge`. Is there a better way to do this?

In `spopt` we install `pulp` via `pip` --> https://github.com/pysal/spopt/blob/4760bd9e03f9b31c003bfa7f5d785a2a81b174bd/ci/312-latest.yaml#L32

2023-12-10 18:41 UTC, jGaboardi commented
Looks like `numpy` is never being imported --> https://github.com/pysal/libpysal/actions/runs/7159612453/job/19493044782?pr=666#step:7:2098

2023-12-10 19:34 UTC, jGaboardi commented
Is [this](https://github.com/pysal/libpysal/actions/runs/7159753204/job/19493357426?pr=666#step:7:1796) passing locally for you?

2023-12-11 20:56 UTC, ljwolf commented
Yes, but fixing that, I still have fails locally. Will fix.

2023-12-14 13:58 UTC, ljwolf commented
One question I had for maintainers: 

I built the spatial matching framework to be able to do cross-pattern queries. So, something like: 

> For all points in pattern X, find at least k matched points in pattern Y such that the total distance of X->Y matches are minimised. 

I think this would be good to expose in `cg`, since it's a general purpose spatial matching function for computational geometry applications. I have something even more general that will probably make it into a separate package for spatial causal inference in python, but the spatial implementation can live here. 

So, would it be OK to grab `_spatial_matching()` from `libpysal.graph._matching` and expose it directly in `libpysal.cg`? I could alternatively define a dispatching function that *requires* the second pattern (`y` argument) to be provided.

2023-12-14 15:47 UTC, jGaboardi commented on libpysal/graph/_matching.py
> +        solver = pulp.COIN(msg=False)
I'm wondering if there is way to simply choose the default installed solver without needing to specific (or is this what's happening here with `pulp.COIN()`?). Implementing that logic would go a long way over in `spopt` >> https://github.com/pysal/spopt/issues/348

cc @gegen07

2023-12-14 15:51 UTC, ljwolf commented on libpysal/graph/_matching.py
> +        solver = pulp.COIN(msg=False)
I think we need to do this, since `pulp.PULP_CBC_CMD()` I think is different from `pulp.COIN_CMD()`, and some students could run `pulp.GUROBI()` but not `pulp.GUROBI_CMD()`. 

I think we should really leave it to pulp to deal with this, rather than specifying COIN.

2023-12-14 15:56 UTC, jGaboardi commented on libpysal/graph/_matching.py
> +        solver = pulp.COIN(msg=False)
Yeah, seems like it would make a nice improvement in `spopt` to have the ability to pass in no solver, and then the default one installed is used [within the `solve()` methods](https://github.com/pysal/spopt/blob/ec36c133fbef6f1cde1b3974d34e69b703eed03a/spopt/locate/p_dispersion.py#L315).

2023-12-14 16:25 UTC, ljwolf commented
The code is ready to review. I'm not sure why the ruff check is failing... I've run the ruff auto formatter myself locally on the submission (2c04acf, 215022d, 273e6ea)

2023-12-14 16:28 UTC, jGaboardi commented
> The code is ready to review. I'm not sure why the ruff check is failing... I've run the ruff auto formatter myself locally on the submission ([2c04acf](https://github.com/pysal/libpysal/commit/2c04acf749ef12c10536e164af95437fbc7e61d4), [215022d](https://github.com/pysal/libpysal/commit/215022db802949c4f2dcadca53d858f2bd594529), [273e6ea](https://github.com/pysal/libpysal/commit/273e6ea27000b8540da604272fb75e34de4cdc7f))

Do you have the most recent `ruff` installed locally? I think there was a fresh version released last night. Could be playing a part.

2023-12-18 11:44 UTC, ljwolf commented
Yes, not quite sure what's up here: 

<img width="667" alt="Screenshot 2023-12-18 at 11 42 40" src="https://github.com/pysal/libpysal/assets/2250995/e2afdc86-5465-4646-9bf4-40c84db22c11">

0.1.8 is the most recent version of ruff, and it fixes nothing both in the CI and locally?

2023-12-18 12:23 UTC, martinfleis commented
It is `ruff-format` that is failing, not `ruff` linter.

2023-12-19 10:46 UTC, ljwolf commented
OK! Wasn't clear on the differences between ruff check and format. Sorry! 

I think this is complete.

2023-12-22 14:52 UTC, jGaboardi requested changes
Looking very cool.

2023-12-22 14:52 UTC, jGaboardi commented on libpysal/graph/_matching.py
> +            stacklevel=1,
This should probably be `stacklevel=2`, if I'm not mistaken.

2023-12-22 14:52 UTC, jGaboardi commented on libpysal/graph/tests/test_matching.py
> +    pulp = pytest.importorskip("pulp")
Let's move this above and skip all tests in the file if `pulp` isn't installed.

2023-12-22 14:52 UTC, jGaboardi commented on libpysal/graph/tests/test_matching.py
> +    if len(default_solver) == 0:
Same for fetching and defining the default solver. This only needs to happen once.

2023-12-22 14:52 UTC, jGaboardi commented on libpysal/graph/tests/test_matching.py
> +    pulp = pytest.importorskip("pulp")
And same with `sklearn`

2023-12-22 15:18 UTC, martinfleis reviewed
The large diff in base is just moving stuff around to get alphabetic order of builders?

Can you also add a test for `Graph.build_spatial_matches` ?

2023-12-22 15:18 UTC, martinfleis commented on ci/310-oldest.yaml
> +  - pulp
```suggestion
  - pip
```

2023-12-22 15:18 UTC, martinfleis commented on ci/312-no-optional.yaml
> +  - scikit-learn
```suggestion
```
No optional dependencies shall be in this env

2023-12-22 15:18 UTC, martinfleis commented on environment.yml
> +  - coin-or-cbc
Why do we have this here and not in CI envs?

2023-12-22 15:18 UTC, martinfleis commented on libpysal/graph/_matching.py
> +from sklearn.metrics import pairwise_distances
So far, sklearn has been a soft dependency for libpysal. Do we want to change that?

2023-12-22 15:19 UTC, jGaboardi commented on ci/312-no-optional.yaml
> +  - scikit-learn
Good catch @martinfleis

2023-12-22 15:20 UTC, jGaboardi commented
> The large diff in base is just moving stuff around to get alphabetic order of builders?
> 
> Can you also add a test for `Graph.build_spatial_matches` ?

Yes.

2023-12-29 00:50 UTC, knaaptime commented on libpysal/graph/_matching.py
> +from sklearn.metrics import pairwise_distances
yes, we decided to change

2023-12-29 00:50 UTC, knaaptime commented on ci/312-no-optional.yaml
> +  - scikit-learn
made it a hard dep

2024-01-17 14:50 UTC, ljwolf commented on ci/312-no-optional.yaml
> +  - scikit-learn
So, I will keep `scikit-learn` in this env?

2024-01-17 14:51 UTC, ljwolf commented on environment.yml
> +  - coin-or-cbc
This was part of my attempt to get pulp installed correctly. Fine to remove.

2024-01-17 15:04 UTC, martinfleis commented on ci/312-no-optional.yaml
> +  - scikit-learn
I suppose so but it needs to make its way to requirements in pyproject.toml if it is becoming hard dep now.

2024-01-17 16:10 UTC, ljwolf commented
I believe I've addressed all comments!

2024-01-17 16:22 UTC, knaaptime approved these changes

2024-01-17 16:26 UTC, jGaboardi approved these changes

2024-01-26 15:42 UTC, ljwolf commented
Hi! could one of the approvers please merge this?

2024-01-26 16:02 UTC, merged

2024-01-26 16:25 UTC, ljwolf commented
thank you!