Refactor handling of coincident points in triangulation
pysal/libpysal pull request #714
Opened 2024-05-29 13:33 UTC by martinfleis

Closes #713 

Had to touch more stuff than intended but we now rely on QHull to identify coincident points and provide a lookup from which we can build cliques. This should ensure that we won't hit the precision issues. 

Some minor cleanup happened alongside, i.e. to avoid solving isolates twice in a row.

2024-05-29 13:49 UTC, ljwolf requested changes

2024-05-29 13:49 UTC, ljwolf commented on libpysal/graph/_triangulation.py
> +        if coincident == "jitter":
As I read the code, I think this has to be implemented this way---the coplanar check happens in QHull, we can't know whether we have to use our jittering until we run the triangulation.  

This means we have a tradeoff: 
- have "two" jitter functions (one for KNN and one for triangulated weights) 
- **or** always jitter inputs when coincident='jitter', regardless of if it's needed. I'd recommend doing it here and in KNN, to keep consistent. 

I think between the two, I'd prefer option 1. What do you think?

2024-05-29 13:49 UTC, ljwolf commented on libpysal/graph/_triangulation.py
> -            adjtable = _induce_cliques(adjtable, coincident_lut, fill_value=fill_value)
Fine to use a different implementation of clique expansion, but can we keep this factored into a function that can be called from [`knn`](https://github.com/pysal/libpysal/blob/main/libpysal/graph/_kernel.py#L267) too?

2024-05-29 14:03 UTC, martinfleis commented on libpysal/graph/_triangulation.py
> +        if coincident == "jitter":
By two jitter functions you mean using the QJ QHull option? We can easily use the same one we have in knn (as done here). 

I would prefer doing the latter and always jitter, even in KNN than having different behaviour in different places solving the same. We still have as we rely on different precision here but it is consistent from user perspective.

2024-05-29 14:49 UTC, jGaboardi commented on libpysal/graph/_triangulation.py
> +        raise ValueError(
Perhaps it might be wise to have our own custom error this, something like `CoplanarError`? Or would that be too involved?

Since similar ones use used in [other methods](https://github.com/pysal/libpysal/blob/181784671da99af1f211cc5a3cbd1f2c4a553ce7/libpysal/graph/_kernel.py#L239), maybe not a bad idea?

2024-05-29 15:01 UTC, ljwolf commented on libpysal/graph/_triangulation.py
> +        raise ValueError(
Also +1 on using "coplanar" throughout, rather than "coincident" and "coplanar"

2024-05-29 15:04 UTC, jGaboardi commented on libpysal/graph/_triangulation.py
> +        raise ValueError(
Good point on that. I was about ask if there was a subtle difference between the two that I wasn't aware of.

2024-05-30 10:23 UTC, martinfleis commented on libpysal/graph/_kernel.py
> -    return _resolve_islands(heads, tails, ids, weights)
`_resolve_islands` is called within `_sparse_to_arrays`, no need to call it twice

2024-05-30 10:23 UTC, martinfleis commented on libpysal/graph/_kernel.py
> +        coordinates, geoms = _jitter_geoms(coordinates, geoms=geoms)
Always jitter if `coplanar == "jitter"`

2024-05-30 10:29 UTC, martinfleis commented
Okay, this is now significantly updated.

- switch terminology from `coincident` to `coplanar` as suggested by @ljwolf  (cc @knaaptime in case you are using "coincident" somewhere in your materials, this is technically a breaking change but we're still in experimental mode)
- knn uses the same coplanar resolver as triangulation. that also required new function to build coplanar lookup to match the one coming from Delaunay
- raising CoplanarError
- always jitter when `coplanar="jitter"`, no matter if there is a coplanar point or not

The performance is about the same as it was before.

2024-05-30 10:59 UTC, ljwolf approved these changes

2024-05-30 13:05 UTC, jGaboardi approved these changes

2024-05-30 13:10 UTC, merged